version: '3'
volumes:
  postgres:
services:
  db:
    container_name: db
    networks:
      - admin-app
    image: postgres:11
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - environments/.env.postgres
  frontend_app:
    restart: on-failure:3
    container_name: frontend-app
    networks:
      - admin-app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./frontend/:/app
    ports:
      - "80:3000"
    env_file:
      - environments/.env.frontend_app
    stdin_open: true
  backend_api:
    restart: on-failure:3
    container_name: backend-api
    networks:
      - admin-app
    build:
      context: ./backend_api
      dockerfile:  Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend_api/:/home/developer/app
    env_file:
      - environments/.env.backend_api
networks:
  admin-app:
    driver: bridge